[colors.primary]
background = '#111319'
foreground = '#e1e2eb'

[colors.cursor]
text = '#111319'
cursor = '#e1e2eb'

[colors.vi_mode_cursor]
text = '#111319'
cursor = '#adc6ff'

[colors.search.matches]
foreground = '#424752'
background = '#f4aeff'

[colors.search.focused_match]
foreground = '#424752'
background = '#adc6ff'

[colors.footer_bar]
foreground = '#424752'
background = '#e1e2eb'

[colors.hints.start]
foreground = '#424752'
background = '#b4c6f3'

[colors.hints.end]
foreground = '#424752'
background = '#b4c6f3'

[colors.selection]
text = '#c2c6d4'
background = '#424752'


[colors.normal]
black   = '#424752'
red     = '#ffb4ab'
green   = '#adc6ff'
yellow  = '#b4c6f3'
blue    = '#f4aeff'
magenta = '#adc6ff'
cyan    = '#b4c6f3'
white   = '#e1e2eb'


[colors.bright]
black   = '#8c909e'
red     = '#ffb4ab'
green   = '#adc6ff'
yellow  = '#b4c6f3'
blue    = '#f4aeff'
magenta = '#adc6ff'
cyan    = '#b4c6f3'
white   = '#e1e2eb'


[colors.dim]
black   = '#424752'
red     = '#ffb4ab'
green   = '#adc6ff'
yellow  = '#b4c6f3'
blue    = '#f4aeff'
magenta = '#adc6ff'
cyan    = '#b4c6f3'
white   = '#e1e2eb'
