[general]
import = ["~/.config/alacritty/themes/warp.toml"]
live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 16, y = 16 }
dynamic_padding = true
decorations = "Full"
opacity = 0.90
title = "Alacritty@CachyOS"
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }
size = 12.0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", mods = "None", action = "PasteSelection" }]

[keyboard]
bindings = [
  { key = "Paste", mods = "None", action = "Paste" },
  { key = "Copy", mods = "None", action = "Copy" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "L", mods = "Control", mode = "~Vi", chars = "\f" },
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward" },
  { key = "C", mods = "Control|Shift", mode = "Vi", action = "ClearSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
]
